[package]
name = "palantir"
license = "MIT OR Apache-2.0"
description = "Work in progress P2P networking library designed for use with Fluxion."
repository = "https://github.com/peperworx/palantir"
version = "0.0.0"
edition = "2021"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.74"
ecdsa = "0.16.9"
futures = "0.3.29"
kanal = "0.1.0-pre8"
p384 = "0.13.0"
rand_core = "0.6.4"
rcgen = "0.11.3"
rustls = { version = "0.21.9", features = ["dangerous_configuration"] }
serde = "1.0.193"
sha2 = "0.10.8"
thiserror = "1.0.50"
tokio = { version = "1.34.0", features = ["full"] }
wtransport = { version = "0.1.8", features = ["dangerous-configuration"] }
