[package]
name = "palantir"
license = "MIT OR Apache-2.0"
description = "Work in progress P2P networking library designed for use with Fluxion."
repository = "https://github.com/peperworx/palantir"
version = "0.0.0"
edition = "2021"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
futures = "0.3.30"
futures-io = "0.3.30"
futures_codec = { version = "0.4.1", features = ["serde"] }
merge-io = "0.3.0"
rand = "0.8.5"
serde = { version = "1.0.193", features = ["derive"] }
sha2 = "0.10.8"
thiserror = "1.0.52"
uuid = { version = "1.6.1", features = ["v5"] }
wtransport = "0.1.10"
